In [2]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib qt
from PCX_sim.core.pcx_functions import mp, eV, CrossSection, CrossSectionCollection, PCX_run#, CrossSectionCollection_dev#, PCX_run_dev
from PCX_sim.core.pcx_functions import read_tokesi_file, cross_section_n_scaling
#from scipy.constants import Boltzmann as kb, electron

In [3]:
cross_sections = CrossSectionCollection()

#He2+ CX cross sections in cm2, collsision with H(1s), producing He+

#He+(1s) excitation cross sections in cm2, collsision with H(1s)



In [6]:
plt.figure()
l = []
for k,v in cross_sections.cross_sections.items():
    if not v==0.0:
        #v.plot()
        print(k)
        l.append(k)
plt.legend(l)
plt.show()
len(l)

He2_Hd_1
He2_Hd_2
He2_Hd_3
He2_Hd_4
He2_Hd_5
He_e_1
He_p_1
He_Hi_1
He_e_2
He_p_2
He_Hi_2
He_e_3
He_p_3
He_Hi_3
He_e_4
He_p_4
He_Hi_4
He_e_5
He_p_5
He_Hi_5
He1_1_e_1
He1_1_p_1
He1_1_Hi_1
He1_2_e_2
He1_2_p_2
He1_2_Hi_2
He1_3_e_3
He1_3_p_3
He1_3_Hi_3
He1_4_e_4
He1_4_p_4
He1_4_Hi_4
He1_5_e_5
He1_5_p_5
He1_5_Hi_5
He1_1_Hd_1
He1_2_Hd_1
He1_3_Hd_1
He1_4_Hd_1
He1_5_Hd_1
He1_1_Hi_2
He1_2_Hi_1
He1_1_Hi_3
He1_3_Hi_1
He1_1_Hi_4
He1_4_Hi_1
He1_1_Hi_5
He1_5_Hi_1
He1_2_Hi_3
He1_3_Hi_2
He1_2_Hi_4
He1_4_Hi_2
He1_2_Hi_5
He1_5_Hi_2
He1_3_Hi_4
He1_4_Hi_3
He1_3_Hi_5
He1_5_Hi_3
He1_4_Hi_5
He1_5_Hi_4
He1_1_e_2
He1_2_e_1
He1_1_e_3
He1_3_e_1
He1_1_e_4
He1_4_e_1
He1_1_e_5
He1_5_e_1
He1_2_e_3
He1_3_e_2
He1_2_e_4
He1_4_e_2
He1_2_e_5
He1_5_e_2
He1_3_e_4
He1_4_e_3
He1_3_e_5
He1_5_e_3
He1_4_e_5
He1_5_e_4
He1_1_p_2
He1_1_p_3
He1_1_p_4
He1_1_p_5
He1_2_p_1
He1_2_p_3
He1_2_p_4
He1_2_p_5
He1_3_p_1
He1_3_p_2
He1_3_p_4
He1_3_p_5
He1_4_p_1
He1_4_p_2
He1_4_p_3
He1_4_p_5
He1_5_p_1
He1_5_p_2
He1_5_p_3
He1_5_p_4


100

In [15]:
t_ref = cross_sections.cross_sections['He1_1_e_1']

In [16]:
t = cross_section_n_scaling(t_ref, 1, 10, 2, 10)

In [17]:
plt.figure()
t_ref.plot()
t.plot()
plt.show()

In [16]:
N = 60000
dt = 1e-12

T_plasma = 1e3
T_H = 1e-2

E_He = 1e6
n_He0 = 7e12

n_plasma = np.full(N, 1e20)
n_H = np.full(N, 1e26)
time = np.arange(N) * dt



comp = PCX_run(n_plasma, T_plasma, n_H, T_H, E_He, n_He0, cross_sections.cross_sections, dt=dt*0.1, N=N)

n_plasma: [1.e+20 1.e+20 1.e+20 ... 1.e+20 1.e+20 1.e+20]
T_plasma: 1000.0
m_plasma: 1
n_H: [1.e+26 1.e+26 1.e+26 ... 1.e+26 1.e+26 1.e+26]
T_H: 0.01
m_H: 1
E_He: 1000000.0
v_He: 6920561.088504181
cross_sections: {'He2_Hd_1': <PCX_sim.core.pcx_functions.CrossSection object at 0x000002038ED6A8D0>, 'He2_Hi_1': 0.0, 'He2_p_1': 0.0, 'He2_e_1': 0.0, 'He2_Hd_2': <PCX_sim.core.pcx_functions.CrossSection object at 0x000002039328AC10>, 'He2_Hi_2': 0.0, 'He2_p_2': 0.0, 'He2_e_2': 0.0, 'He2_Hd_3': <PCX_sim.core.pcx_functions.CrossSection object at 0x0000020390D37CD0>, 'He2_Hi_3': 0.0, 'He2_p_3': 0.0, 'He2_e_3': 0.0, 'He2_Hd_4': <PCX_sim.core.pcx_functions.CrossSection object at 0x0000020393296D90>, 'He2_Hi_4': 0.0, 'He2_p_4': 0.0, 'He2_e_4': 0.0, 'He2_Hd_5': <PCX_sim.core.pcx_functions.CrossSection object at 0x00000203931BB1D0>, 'He2_Hi_5': 0.0, 'He2_p_5': 0.0, 'He2_e_5': 0.0, 'He_e_1': <PCX_sim.core.pcx_functions.CrossSection object at 0x000002038ED56890>, 'He_p_1': <PCX_sim.core.pcx_functions.C

C:\Users\balazs\plazma\codes\PCX_sim\core\pcx_functions.py:311: ODEintWarning: Integration successful.
  self.n_He = odeint(calculate_dndt, self.n_He, self.time, args=(dn_He, self), printmessg=True).T


In [10]:
plt.figure()
for n in comp.n_He:
    plt.plot(comp.time, n)
plt.yscale('log')
plt.xscale('log')
plt.ylabel(r'Density [m$^{-3}$]')
plt.xlabel('Time [s]')
plt.title('')
#plt.legend(['He', r'He$^+$', r'He$^{2+}$'])
#plt.savefig(f'plots/example.png', bbox_inches='tight')
plt.show()

In [73]:
plt.figure()
for n in comp.n_He:
    plt.plot(np.abs(np.diff(n))/n[1:])
plt.yscale('log')
plt.show()

C:\Users\balazs\AppData\Local\Temp\ipykernel_21024\1110205115.py:3: RuntimeWarning: invalid value encountered in divide
  plt.plot(np.abs(np.diff(n))/n[1:])


In [108]:
N = 60000
dt = 1e-12

T_plasma = 10e3
T_H = 1e-2

E_He = 1e6
n_He0 = 1e17

n_plasma = np.full(N, 1e20)
n_H = np.full(N, 1e26)
time = np.arange(N) * dt



comp2 = PCX_run(n_plasma, T_plasma, n_H, T_H, E_He, n_He0, cross_sections.cross_sections, dt=dt*0.1, N=N, implicit_num=200)

n_plasma: [1.e+20 1.e+20 1.e+20 ... 1.e+20 1.e+20 1.e+20]
T_plasma: 10000.0
m_plasma: 1
n_H: [1.e+26 1.e+26 1.e+26 ... 1.e+26 1.e+26 1.e+26]
T_H: 0.01
m_H: 1
E_He: 1000000.0
v_He: 6920561.088504181
cross_sections: {'He2_Hd_1': <PCX_sim.core.pcx_functions.CrossSection object at 0x000001D5A8B67610>, 'He2_Hi_1': 0.0, 'He2_p_1': 0.0, 'He2_e_1': 0.0, 'He2_Hd_2': <PCX_sim.core.pcx_functions.CrossSection object at 0x000001D5A6739F90>, 'He2_Hi_2': 0.0, 'He2_p_2': 0.0, 'He2_e_2': 0.0, 'He2_Hd_3': <PCX_sim.core.pcx_functions.CrossSection object at 0x000001D5A8B523D0>, 'He2_Hi_3': 0.0, 'He2_p_3': 0.0, 'He2_e_3': 0.0, 'He2_Hd_4': <PCX_sim.core.pcx_functions.CrossSection object at 0x000001D5A8B67110>, 'He2_Hi_4': 0.0, 'He2_p_4': 0.0, 'He2_e_4': 0.0, 'He2_Hd_5': <PCX_sim.core.pcx_functions.CrossSection object at 0x000001D5A8B64F50>, 'He2_Hi_5': 0.0, 'He2_p_5': 0.0, 'He2_e_5': 0.0, 'He_e_1': <PCX_sim.core.pcx_functions.CrossSection object at 0x000001D5A8B534D0>, 'He_p_1': <PCX_sim.core.pcx_functions.

In [ ]:
plt.figure()
for i in range(7):
    plt.plot(comp2.implicit_checker[-1, :, i])
plt.show()

In [84]:
plt.figure()
plt.plot(comp2.implicit_checker[-1, :, 1])
plt.show()

In [81]:
comp2.implicit_checker[-1, :, 1]

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, na

In [85]:
plt.figure()
for n in comp2.n_He:
    plt.plot(np.diff(n))
#plt.yscale('log')
plt.show()

In [109]:
plt.figure()
for n in comp2.n_He:
    plt.plot(comp2.time, n)
plt.yscale('log')
plt.xscale('log')
plt.ylabel(r'Density [m$^{-3}$]')
plt.xlabel('Time [s]')
plt.title('')
#plt.legend(['He', r'He$^+$', r'He$^{2+}$'])
#plt.savefig(f'plots/example.png', bbox_inches='tight')
plt.show()

In [24]:
plt.figure()
for n in comp2.n_He:
    plt.plot(comp2.time, n)
plt.yscale('log')
plt.xscale('log')
plt.ylabel(r'Density [m$^{-3}$]')
plt.xlabel('Time [s]')
plt.title('')
#plt.legend(['He', r'He$^+$', r'He$^{2+}$'])
#plt.savefig(f'plots/example.png', bbox_inches='tight')
plt.show()

In [505]:
comp2.n_He[:, -1]

array([3.47149848e+14, 8.99163148e+15, 7.85458271e+15, 7.14629785e+15,
       6.93527354e+15, 6.80757523e+15, 6.19174894e+16])

In [509]:
comp2.n_He[:, -1]

array([3.47149848e+14, 8.99421775e+15, 7.84397220e+15, 7.17391887e+15,
       7.05390104e+15, 6.66935095e+15, 6.19174894e+16])

In [65]:
plt.figure()
plt.plot(comp2.dist, comp2.n_He[0])
plt.plot(comp2.dist, comp2.n_He[1])
plt.plot(comp2.dist, comp2.n_He[2])
plt.yscale('log')
plt.xscale('log')
plt.ylabel(r'Density [m$^{-3}$]')
plt.xlabel('Distance [m]')
plt.title('')
plt.legend(['He', r'He$^+$', r'He$^{2+}$'])
#plt.savefig(f'plots/example.png', bbox_inches='tight')
plt.show()

In [207]:
plt.figure()
plt.plot(comp.time, comp.n_He1)
plt.plot(comp2.time, comp2.n_He[1]*5)
plt.yscale('log')
plt.xscale('log')
plt.ylabel(r'Density [m$^{-3}$]')
plt.xlabel('Time [s]')
plt.title('')
plt.legend(['original', 'dev'])
#plt.savefig(f'plots/example.png', bbox_inches='tight')
plt.show()

In [8]:
def gaussian(A, x, x0, s):
    return A*np.exp(-(x-x0)**2/s**2)

In [9]:
dist = np.linspace(0, 0.1, 10000)

n_H3 = gaussian(n_H, dist, 0.02, 0.003)
#n_H3 = np.zeros_like(n_H2)
n_plasma3 = ((n_H - n_H3) / n_H) * n_plasma


In [10]:
comp3 = PCX_run_dev(n_plasma3, T_plasma, n_H3, T_H, E_He, n_He0, cross_sections, z=dist)

In [11]:
#plt.plot(dist, n_H3)
plt.plot(dist, n_plasma3)
#plt.yscale('log')
plt.show()

In [12]:
plt.plot(comp3.dist, comp3.n_He[0])
plt.plot(comp3.dist, comp3.n_He[1])
plt.plot(comp3.dist, comp3.n_He[2])
#plt.yscale('log')
#plt.xscale('log')
plt.ylabel(r'Density [m$^{-3}$]')
plt.xlabel('Distance [m]')
plt.title('')
plt.legend(['He', r'He$^+$', r'He$^{2+}$'])
#plt.savefig(f'plots/example.png', bbox_inches='tight')
plt.show()

In [13]:
plt.plot(comp3.dist[1:], np.diff(comp3.n_He[2]))
plt.plot(comp3.dist[1:], np.diff(comp3.n_He[1]))
plt.show()

In [14]:
comp3.rate_coeff_matrix

array([[2.50082737e-15, 4.19207258e-14, 0.00000000e+00, 3.94260631e-14],
       [1.07440627e-37, 8.10317655e-15, 3.62898711e-16, 4.86439483e-15],
       [0.00000000e+00, 0.00000000e+00, 1.24471140e-15, 0.00000000e+00]])

In [116]:
plt.figure()
for k,v in cross_sections_dev.cross_sections.items():
    if 'He1_5' in k and 'Hi' in k:
        v.plot()
#plt.legend()
plt.show()

In [121]:
comp2.rate_coeff_matrix

array([[5.00165474e-16, 5.00165474e-16, 5.00165474e-16, 5.00165474e-16,
        5.00165474e-16, 8.38275537e-15, 8.38275537e-15, 8.38275537e-15,
        8.38275537e-15, 8.38275537e-15, 7.88521262e-15, 7.88521262e-15,
        7.88521262e-15, 7.88521262e-15, 7.88521262e-15, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.07440627e-37, 8.37134678e-17, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 8.10256138e-15, 7.05875853e-15, 7.05875853e-15,
        7.05875853e-15, 7.05875853e-15, 4.86439483e-15, 7.37387267e-15,
        1.16384009e-15, 4.32580500e-16, 2.14954855e-16, 3.62898711e-16,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [6.39975551e-14, 1.07440627e-37, 6.75085664e-12, 8.38570439e-13,
        1.95259533e-13, 7.05875853e-15, 8.10256138e-15, 7.05875853e-15,
        7.05875853e-15, 7.05875853e-15, 1.84364135e-15, 4.86439483e-15,
        7.37387267e-14, 1.16384009e-14, 4.32580500e-15, 3.6289

In [124]:
spont_deex_file = '../cross_sections/He_excitation/spontaneous_deex.txt'

rates = []
with open(spont_deex_file, 'r') as f:
    f.readline()
    for line in f.readlines():
        splitted = line.replace('\"', '').split('\t')
        rates.append([splitted[4], splitted[8], splitted[11]])

In [127]:
rates

[['3.1586e+08', '1s', '6p'],
 ['3.1583e+08', '1s', '6p'],
 ['5.5036e+08', '1s', '5p'],
 ['5.5033e+08', '1s', '5p'],
 ['1.0917e+09', '1s', '4p'],
 ['1.0917e+09', '1s', '4p'],
 ['2.6778e+09', '1s', '3p'],
 ['2.6777e+09', '1s', '3p'],
 ['1.0029e+10', '1s', '2p'],
 ['1.0030e+10', '1s', '2p'],
 ['6.8658e+07', '2p', '6d'],
 ['3.9232e+06', '2p', '6s'],
 ['4.5764e+07', '2s', '6p'],
 ['4.5768e+07', '2s', '6p'],
 ['8.2376e+07', '2p', '6d'],
 ['1.3729e+07', '2p', '6d'],
 ['7.8495e+06', '2p', '6s'],
 ['1.2577e+08', '2p', '5d'],
 ['6.8782e+06', '2p', '5s'],
 ['7.9227e+07', '2s', '5p'],
 ['7.9234e+07', '2s', '5p'],
 ['1.5091e+08', '2p', '5d'],
 ['2.5150e+07', '2p', '5d'],
 ['1.3762e+07', '2p', '5s'],
 ['2.7523e+08', '2p', '4d'],
 ['1.5479e+08', '2s', '4p'],
 ['1.3762e+07', '2p', '4s'],
 ['1.5481e+08', '2s', '4p'],
 ['3.3023e+08', '2p', '4d'],
 ['5.5036e+07', '2p', '4d'],
 ['2.7534e+07', '2p', '4s'],
 ['8.6268e+08', '2p', '3d'],
 ['3.5939e+08', '2s', '3p'],
 ['3.3700e+07', '2p', '3s'],
 ['3.5946e+08'

In [128]:
rate_dict = {}
for upper in range(2,6):
    for lower in range(1,upper):
        rate = []
        for data in rates:
            if str(lower) in data[1] and str(upper) in data[2]:
                rate.append(float(data[0]))
        rate_dict[f'{upper}-{lower}'] = np.array(rate)

In [130]:
for k,v in rate_dict.items():
    plt.plot(v, label=k)
plt.yscale('log')
plt.legend()
plt.show()

In [131]:
summed_dict = {}
for k,v in rate_dict.items():
    summed_dict[k] = np.mean(v)

In [133]:
emission_matrix = np.zeros((5,5))
for k,v in summed_dict.items():
    emission_matrix[int(k[2])-1, int(k[0])-1] = v

In [135]:
summed_dict

{'2-1': 10029500000.0,
 '3-1': 2677750000.0,
 '3-2': 412897142.85714287,
 '4-1': 1091700000.0,
 '4-2': 144484571.42857143,
 '4-3': 61966796.92307692,
 '5-1': 550345000.0,
 '5-2': 68704457.14285715,
 '5-3': 25059987.692307692,
 '5-4': 16218452.421052631}

In [136]:
np.sum(emission_matrix, axis=1)

array([1.43492950e+10, 6.26086171e+08, 8.70267846e+07, 1.62184524e+07,
       0.00000000e+00])

In [137]:
emission_matrix.dot(np.array([1,1,1,1,1]))

array([1.43492950e+10, 6.26086171e+08, 8.70267846e+07, 1.62184524e+07,
       0.00000000e+00])

In [141]:
emission_matrix

array([[0.00000000e+00, 1.00295000e+10, 2.67775000e+09, 1.09170000e+09,
        5.50345000e+08],
       [0.00000000e+00, 0.00000000e+00, 4.12897143e+08, 1.44484571e+08,
        6.87044571e+07],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 6.19667969e+07,
        2.50599877e+07],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.62184524e+07],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00]])

In [146]:
comp2.emission_matrix.dot(comp2.n_He[1:-1,-1])*comp2.dt

array([6.21807710e+12, 4.26912427e+11, 8.82369342e+10, 2.20749363e+10,
       0.00000000e+00])

In [160]:
comp2.n_He[1:-1,-1]

array([7.20895278e+15, 3.16238087e+15, 5.01800544e+15, 8.73496560e+15,
       1.36110004e+16])

In [162]:
3.16e15*1.0029e10

3.169164e+25

In [165]:
(comp2.emission_matrix.dot(comp2.n_He[1:-1,-1]) - np.sum(emission_matrix * comp2.n_He[1:-1,-1], axis=0))*comp2.dt

array([ 6.21807710e+12, -2.74479747e+12, -1.46265148e+12, -1.11185582e+12,
       -8.98772328e+11])

In [156]:
a = np.array([[1,2],[4,5]])
b = np.array([1,2])

In [158]:
a*b

array([[ 1,  4],
       [ 4, 10]])

In [3]:
def oscillator_strength(n1, n2):
    return 0.42/(n2 - n1)**3

In [4]:
Ry = 13.60569

In [5]:
def delta_E(Z, lower_n, upper_n):
    return Z**2*Ry*(1/lower_n**2 - 1/upper_n**2)

In [6]:
def cross_section_n_scaling(sigma_orig:CrossSection, n1_orig, n2_orig, n1_new, n2_new, z=2):

    de_orig = delta_E(z, n1_orig, n2_orig)
    de_new = delta_E(z, n1_new, n2_new)
    f_orig = oscillator_strength(n1_orig, n2_orig)
    f_new = oscillator_strength(n1_new, n2_new)
    new_energies = sigma_orig.energy * (de_new / de_orig)
    new_values = sigma_orig.cross_section_m2 * (f_new / f_orig) * (de_orig / de_new)**2
    return CrossSection(sigma_orig.projectile, sigma_orig.target, sigma_orig.product, energy=new_energies, values=new_values)

In [17]:
t = cross_sections.cross_sections['He1_2_e_3']
t_ref = cross_sections.cross_sections['He1_2_e_5']

In [18]:
t2 = cross_section_n_scaling(t, 2, 3, 2, 5)

In [19]:
t.plot()
t2.plot()
t_ref.plot()
plt.show()

In [28]:
t2.energy

array([   30985.065     ,    33224.26957136,    35625.2952366 ,
          38199.83635665,    40960.43241139,    43920.52907411,
          47094.54369952,    50497.93554452,    54147.28106358,
          58060.35464546,    62256.21518462,    66755.29890889,
          71579.51891551,    76752.37190037,    82299.05260031,
          88246.57650581,    94623.91144181,   101462.11865746,
         108794.50411212,   116656.78069429,   125087.24216374,
         134126.94966384,   143819.93171277,   154213.39864736,
         165357.97256438,   177307.93387886,   190121.48570068,
         203861.03731674,   218593.50815977,   234390.65374396,
         251329.41515522,   269492.29379797,   288967.75322394,
         309850.65      ,   332242.69571359,   356252.95236604,
         381998.3635665 ,   409604.32411395,   439205.29074108,
         470945.43699517,   504979.35544525,   541472.81063584,
         580603.54645462,   622562.15184623,   667552.98908893,
         715795.18915507,   767523.71900

In [24]:
t.energy

array([   36723.04      ,    39376.91208457,    42222.57213227,
          45273.8801264 ,    48545.69767276,    52053.96038413,
          55815.75549572,    59849.40508981,    64174.55533462,
          68812.2721724 ,    73785.14392252,    79117.39129943,
          84834.98538134,    90965.77410414,    97539.61789666,
         104588.535118  ,   112146.85800511,   120251.39989033,
         128941.63450325,   138259.88823027,   148251.54626813,
         158965.27367566,   170453.25240032,   182771.43543391,
         195979.81933556,   210142.73644902,   225329.16823784,
         241613.08126429,   259073.78744861,   277796.33036322,
         297871.89944323,   319398.27413093,   342480.30011726,
         367230.4       ,   393769.12084574,   422225.72132271,
         452738.80126401,   485456.97672764,   520539.60384128,
         558157.55495724,   598494.05089807,   641745.55334618,
         688122.72172399,   737851.43922516,   791173.91299428,
         848349.85381342,   909657.74104

In [13]:
delta_E(2, 1, 3)

48.37578666666666